DROP TABLE IF EXISTS "customer_restaurant" CASCADE ;
DROP TABLE IF EXISTS "restaurant";
DROP TABLE IF EXISTS "customer" CASCADE;
DROP TABLE IF EXISTS "orders";
DROP SEQUENCE IF EXISTS order_sequence;
DROP SEQUENCE IF EXISTS customer_sequence;
DROP SEQUENCE IF EXISTS customer_restaurant_sequence;
DROP SEQUENCE IF EXISTS restaurant_sequence;
--
--TABLE: CUSTOMER
--
CREATE TABLE "customer"(
  CUSTOMER_ID INTEGER PRIMARY KEY,
  NAME VARCHAR(50),
  SURNAME VARCHAR(50),
  AGE INTEGER,
  SEX CHAR(1) CHECK(SEX='M' OR SEX='F')
);
--
--TABLE: ORDER
--
CREATE TABLE "orders"(
  ORDER_ID INTEGER PRIMARY KEY,
  CUSTOMER_ID INTEGER UNIQUE,
  DATE_OF_ORDER DATE,
  NUMBER_OF_PRODUCTS INTEGER,
  ORDER_AMOUNT INTEGER
);
--
--TABLE: RESTAURANT
--
CREATE TABLE "restaurant"(
  RESTARAUNT_ID INTEGER PRIMARY KEY,
  NAME VARCHAR(100),
  ADDRESS VARCHAR(100),
  RATING INTEGER CHECK (RATING BETWEEN 1 AND 10),
  KITCHEN_TYPE VARCHAR(50)
);
--
--TABLE: CUSTOMER_RESTAURANT
--
CREATE TABLE "customer_restaurant"(
  CUSTOMER_RESTARAUNT_ID INTEGER PRIMARY KEY,
  CUSTOMER_ID INTEGER,
  RESTARAUNT_ID INTEGER
);
--
--ALTER TABLE: ORDER
--
ALTER TABLE "orders" ADD CONSTRAINT RefORDtoCUS
FOREIGN KEY (CUSTOMER_ID) REFERENCES "customer"(CUSTOMER_ID);
--
--ALTER TABLE: CUSTOMER_RESTAURANT
--
ALTER TABLE "customer_restaurant" ADD CONSTRAINT RefCUS
FOREIGN KEY (CUSTOMER_ID) REFERENCES "customer"(CUSTOMER_ID);
--
--ALTER TABLE CUSTOMER_RESTAURANT
--
ALTER TABLE "customer_restaurant" ADD CONSTRAINT RefRES
FOREIGN KEY (RESTARAUNT_ID) REFERENCES "restaurant"(RESTARAUNT_ID);
--
--SEQUENCE: order_sequence
--
CREATE SEQUENCE order_sequence
INCREMENT 1
MINVALUE 1
MAXVALUE 9223372036854775807
START 2
CACHE 1;
--
--SEQUENCE: customer_sequence
--
CREATE SEQUENCE customer_sequence
INCREMENT 1
MINVALUE 1
MAXVALUE 9223372036854775807
START 2
CACHE 1;
--
--SEQUENCE: restaurant_sequence
--
CREATE SEQUENCE restaurant_sequence
INCREMENT 1
MINVALUE 1
MAXVALUE 9223372036854775807
START 2
CACHE 1;
--
--SEQUENCE: customer_restaurant_sequence
--
CREATE SEQUENCE customer_restaurant_sequence
INCREMENT 1
MINVALUE 1
MAXVALUE 9223372036854775807
START 2
CACHE 1;
--
-- INSERT: CUSTOMER
--
INSERT INTO "customer" VALUES (1, 'Dmitry', 'Kluev', 21, 'M');
INSERT INTO "customer" VALUES (2, 'Egor', 'Kulikov', 18, 'M');
--
--INSERT: ORDER
--
INSERT INTO "orders" VALUES (1, 1, '01.01.16', 21, 4500);
INSERT INTO "orders" VALUES (2, 2, '01.01.16', 18, 3800);
--
--INSERT: RESTAURANT
--
INSERT INTO "restaurant" VALUES (1, 'Origato', 'Wayne Street', 9, 'Japanese');
INSERT INTO "restaurant" VALUES (2, 'Ashot', 'Boll Street', 5, 'Caucasian');
--
--INSERT: CUSTOMER_RESTAURANT
--
INSERT INTO "customer_restaurant" VALUES (1, 1, 1);
INSERT INTO "customer_restaurant" VALUES (2, 1, 2);