DROP TABLE IF EXISTS "order_line" CASCADE ;
DROP TABLE IF EXISTS "dish" CASCADE ;
DROP TABLE IF EXISTS "customer" CASCADE;
DROP TABLE IF EXISTS "orders" CASCADE;
DROP SEQUENCE IF EXISTS order_sequence;
DROP SEQUENCE IF EXISTS customer_sequence;
DROP SEQUENCE IF EXISTS order_line_sequence;
DROP SEQUENCE IF EXISTS dish_sequence;
--
--TABLE: CUSTOMER
--
CREATE TABLE "customer"(
  CUSTOMER_ID INTEGER PRIMARY KEY,
  NAME VARCHAR(50) NOT NULL ,
  SURNAME VARCHAR(50) NOT NULL ,
  AGE INTEGER,
  SEX CHAR(1) CHECK(SEX='M' OR SEX='F')
);
--
--TABLE: ORDER
--
CREATE TABLE "orders"(
  ORDER_ID INTEGER PRIMARY KEY,
  CUSTOMER_ID INTEGER,
  DATE_OF_ORDER DATE,
  NUMBER_OF_PRODUCTS INTEGER
--   COST INTEGER
);
--
--TABLE: DISH
--
CREATE TABLE "dish"(
  DISH_ID INTEGER PRIMARY KEY,
  NAME VARCHAR(100) NOT NULL ,
  COST INTEGER
);
--
--TABLE: ORDER_LINE
--
CREATE TABLE "order_line"(
  ORDER_LINE_ID INTEGER PRIMARY KEY,
  ORDER_ID INTEGER,
  DISH_ID INTEGER,
  COUNT INTEGER
--   COST INTEGER
);
--
--ALTER TABLE: ORDER
--
ALTER TABLE "orders" ADD CONSTRAINT RefORDtoCUS
FOREIGN KEY (CUSTOMER_ID) REFERENCES "customer"(CUSTOMER_ID);
--
--ALTER TABLE: CUSTOMER_RESTAURANT
--
ALTER TABLE "order_line" ADD CONSTRAINT RefOLtoORD
FOREIGN KEY (ORDER_ID) REFERENCES "orders"(ORDER_ID);
--
--ALTER TABLE CUSTOMER_RESTAURANT
--
-- ALTER TABLE "order_line" ADD CONSTRAINT RefOLtoDISH
-- FOREIGN KEY (DISH_ID) REFERENCES "dish"(DISH_ID);
--
--SEQUENCE: order_sequence
--
CREATE SEQUENCE order_sequence
INCREMENT 1
MINVALUE 1
MAXVALUE 9223372036854775807
START 100
CACHE 10;
--
--SEQUENCE: customer_sequence
--
CREATE SEQUENCE customer_sequence
INCREMENT 1
MINVALUE 1
MAXVALUE 9223372036854775807
START 100
CACHE 10;
--
--SEQUENCE: dish_sequence
--
CREATE SEQUENCE dish_sequence
INCREMENT 1
MINVALUE 1
MAXVALUE 9223372036854775807
START 100
CACHE 10;
--
--SEQUENCE: order_line_sequence
--
CREATE SEQUENCE order_line_sequence
INCREMENT 1
MINVALUE 1
MAXVALUE 9223372036854775807
START 100
CACHE 10;
--
-- INSERT: CUSTOMER
--
INSERT INTO "customer" VALUES (1, 'Dmitry', 'Kluev', 21, 'M');
INSERT INTO "customer" VALUES (2, 'Egor', 'Kulikov', 18, 'M');
INSERT INTO "customer" VALUES (3, 'Evgen', 'Comedian', 23, 'M');
INSERT INTO "customer" VALUES (4, 'Alvaro', 'Cortez', 25,'M');
INSERT INTO "customer" VALUES (5, 'Nico', 'Belucci', 19, 'M');
INSERT INTO "customer" VALUES (6, 'Alisa', 'Mirror', 18, 'F');
--
--INSERT: ORDER
--
INSERT INTO "orders" VALUES (1, 1, '01.01.16', 21);
INSERT INTO "orders" VALUES (2, 2, '01.01.16', 18);
--
--INSERT: RESTAURANT
--
INSERT INTO "dish" VALUES (1, 'Sup', 10);
INSERT INTO "dish" VALUES (2, 'Shit', 5);
INSERT INTO "dish" VALUES (3, 'Pizza', 50);
--
--INSERT: CUSTOMER_RESTAURANT
--
INSERT INTO "order_line" VALUES (1, 1, 1, 10);
INSERT INTO "order_line" VALUES (2, 1, 2, 10);

SELECT * FROM orders;
SELECT * FROM order_line;
SELECT * FROM customer;
SELECT * FROM dish;