DROP TABLE IF EXISTS "CUSTOMER_RESTAURANT" CASCADE ;
DROP TABLE IF EXISTS "RESTAURANT";
DROP TABLE IF EXISTS "CUSTOMER" CASCADE;
DROP TABLE IF EXISTS "ORDER";
--
--TABLE: CUSTOMER
--
CREATE TABLE "CUSTOMER"(
  CUSTOMER_ID INTEGER PRIMARY KEY,
  NAME VARCHAR(50),
  SURNAME VARCHAR(50),
  AGE INTEGER,
  SEX CHAR(1) CHECK(SEX='M' OR SEX='F')
);
--
--TABLE: ORDER
--
CREATE TABLE "ORDER"(
  ORDER_ID INTEGER PRIMARY KEY,
  CUSTOMER_ID INTEGER UNIQUE,
  DATE_OF_ORDER DATE,
  NUMBER_OF_PRODUCTS INTEGER,
  ORDER_AMOUNT INTEGER
);
--
--TABLE: RESTAURANT
--
CREATE TABLE "RESTAURANT"(
  RESTARAUNT_ID INTEGER PRIMARY KEY,
  NAME VARCHAR(100),
  ADDRESS VARCHAR(100),
  RATING INTEGER CHECK (RATING BETWEEN 1 AND 10),
  COOK_TYPE VARCHAR(50)
);
--
--TABLE: CUSTOMER_RESTAURANT
--
CREATE TABLE "CUSTOMER_RESTAURANT"(
  CUSTOMER_RESTARAUNT_ID INTEGER PRIMARY KEY,
  CUSTOMER_ID INTEGER,
  RESTARAUNT_ID INTEGER
);
--
--ALTER TABLE: ORDER
--
ALTER TABLE "ORDER" ADD CONSTRAINT RefORDtoCUS
FOREIGN KEY (CUSTOMER_ID) REFERENCES "CUSTOMER"(CUSTOMER_ID);
--
--ALTER TABLE: CUSTOMER_RESTAURANT
--
ALTER TABLE "CUSTOMER_RESTAURANT" ADD CONSTRAINT RefCUS
FOREIGN KEY (CUSTOMER_ID) REFERENCES "CUSTOMER"(CUSTOMER_ID);
--
--ALTER TABLE CUSTOMER_RESTAURANT
--
ALTER TABLE "CUSTOMER_RESTAURANT" ADD CONSTRAINT RefRES
FOREIGN KEY (RESTARAUNT_ID) REFERENCES "RESTAURANT"(RESTARAUNT_ID);
--
-- INSERT: